# Generated by Django 3.0.3 on 2020-03-21 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200320_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topdealamazon',
            name='image',
        ),
        migrations.RemoveField(
            model_name='topdealflipkart',
            name='image',
        ),
    ]
